services:
  onlyoffice:
    restart: "no"
    image: onlyoffice/documentserver:8.1
    container_name: onlyoffice
    environment:
      JWT_ENABLED: "${ONLYOFFICE_JWT_ENABLED:-true}"
      JWT_SECRET: "${ONLYOFFICE_JWT_SECRET:-super-secret}"
      TZ: ${TZ:-Asia/Seoul}
    ports:
      - "${ONLYOFFICE_PORT:-8081}:80"

#  portal:
#    restart: "no"
#    build: ..
#    container_name: portal
#    depends_on:
#      - db
#      - onlyoffice
#    environment:
#      SPRING_DATASOURCE_URL: "jdbc:mysql://amgw-db.cjmik2sqe1xf.ap-northeast-2.rds.amazonaws.com:3306/gw?useSSL=true&serverTimezone=Asia/Seoul"
#      SPRING_DATASOURCE_USERNAME: gwapp
#      SPRING_DATASOURCE_PASSWORD: GwApp!2025
#      ONLYOFFICE_URL: "http://onlyoffice"   # 내부 통신용
#      ONLYOFFICE_JWT_SECRET: "${ONLYOFFICE_JWT_SECRET:-super-secret}"
#      TZ: ${TZ:-Asia/Seoul}
#    ports:
#      - "18080:8080"
#    volumes:
#      - ./files:/app/files  # 로컬 저장 쓸 때

volumes:
  mysql-data:
