services:
  nextcloud:
    image: nextcloud:28-apache
    container_name: nextcloud
    ports:
      - "8085:80"
    environment:
      - MYSQL_HOST=amgw-db.cjmik2sqe1xf.ap-northeast-2.rds.amazonaws.com
      - MYSQL_DATABASE=gw
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=GwApp!2025
      - REDIS_HOST=redis
      - REDIS_HOST_PORT=6379
      - NEXTCLOUD_CONFIG_EXTRA={"system":{"allow_local_remote_servers":true}}
    depends_on:
      - onlyoffice
      - redis
    volumes:
      - nextcloud_data:/var/www/html
    restart: unless-stopped
    networks:
      - gw-net

  onlyoffice:
    image: onlyoffice/documentserver:8.1
    container_name: onlyoffice
    ports:
      - "8086:80"
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=4c1e7b8adf9df0a0b2e8f1c6a2d90f1c4a0f9e1d5b3a7c6e3f0d2a1b9c8d7e6
      - JWT_HEADER=${ONLYOFFICE_JWT_HEADER:-Authorization}
      - TZ=${TZ:-Asia/Seoul}
    restart: unless-stopped
    networks:
      - gw-net

  redis:
    image: redis:7-alpine
    container_name: redis
    networks: [gw-net]
    restart: unless-stopped

volumes:
  nextcloud_data:

networks:
  gw-net:
    driver: bridge
