services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gw
      TZ: ${TZ}
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_0900_ai_ci"
      ]
    ports:
      - "${MYSQL_HOST_PORT:-3307}:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks: [gw]

  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.file.filename=/etc/traefik/traefik_dynamic.yml"
      - "--entrypoints.web.address=:80"
    ports:
      - "${PROXY_HTTP_PORT}:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./reverse-proxy/traefik_dynamic.yml:/etc/traefik/traefik_dynamic.yml:ro
    networks: [gw]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"

  keycloak-db:
    image: postgres:16
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KC_DB_USERNAME}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
      TZ: ${TZ}
    volumes:
      - kcdb:/var/lib/postgresql/data
    networks: [gw]

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: ${KC_DB}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_HOSTNAME_URL: http://${KC_HOSTNAME}
      TZ: ${TZ}
    command: ["start-dev"]
    depends_on:
      - keycloak-db
    networks: [gw]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.keycloak.rule=Host(`${KC_HOSTNAME}`)"
      - "traefik.http.services.keycloak.loadbalancer.server.port=8080"

  nextcloud-db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: ${NEXTCLOUD_DB_PASS}
      MARIADB_DATABASE: nextcloud
      MARIADB_USER: nextcloud
      MARIADB_PASSWORD: ${NEXTCLOUD_DB_PASS}
      TZ: ${TZ}
    volumes:
      - ncdb:/var/lib/mysql
    networks: [gw]

  nextcloud:
    image: nextcloud:28
    depends_on:
      - nextcloud-db
    environment:
      TZ: ${TZ}
    volumes:
      - ncdata:/var/www/html
      - ./nextcloud/config:/var/www/html/config
    networks: [gw]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`${NEXTCLOUD_HOST}`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

  onlyoffice:
    image: onlyoffice/documentserver:8.1
    environment:
      TZ: ${TZ}
    networks: [gw]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.onlyoffice.rule=Host(`${ONLYOFFICE_HOST}`)"
      - "traefik.http.services.onlyoffice.loadbalancer.server.port=80"

networks:
  gw: {}

volumes:
  kcdb: {}
  ncdb: {}
  ncdata: {}
  mysqldata: {}

